services:
  - type: web
    name: celestia-astro-api-indrajeet
    runtime: docker
    plan: free
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    autoDeploy: true
    envVars:
      - key: GOOGLE_APPS_SCRIPT_URL
        sync: false
      - key: GOOGLE_APPS_SCRIPT_TOKEN
        sync: false
