services:
  - type: web
    name: celestia-astro-api-indrajeet
    runtime: docker
    plan: free
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    autoDeploy: true
    envVars:
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false